### ISSUE TITLE
support HOOBS out of the box

### ISSUE THREAD

**Issue by tetanus** [AntonioMeireles/homebridge-vieramatic#14]
I’m getting an error message with the latest update, and the plugin no longer works:
```
[Homebridge] [4/4/2020, 7:42:13 AM] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [PanasonicVieraTV] Vieramatic Init [Homebridge] [4/4/2020, 7:42:13 AM] Loading 1 accessories...
[Homebridge] [4/4/2020, 7:42:16 AM] [PanasonicVieraTV] Ignoring TV (at '192.168.1.65') as it is unreachable. Likely to be powered off.
```

My configuration is:
```json
{
    "platform": "PanasonicVieraTV",
    "tvs": [
        {
            "ipAddress": "192.168.1.65",
            "name": "Bedroom TV",
            "hdmiInputs": [
                {
                    "id": "1",
                    "name": "Switch"
                },
                {
                    "id": "2",
                    "name": "Apple TV"
                },
                {
                    "id": "3",
                    "name": "Wii U"
                },
                {
                    "id": "4",
                    "name": "NES"
                }
            ]
        }
    ]
}
```
Hardware: Raspberry Pi 3 Model B
Version: a02082 - Rev. 1.2
Homebridge version: HOOBS Version 3.1.23
Vieramatic plugin version: 0.9.7
TV mode: Panasonic TH-55EZ950S

I’m sorry, I don’t how to get the contents of accessories/vieramatic.json or generate logs from HOOBS. 

The following is from the Advanced section in HOOBS:
```json
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYFF6K",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "SG",
        "postal_code": "390999",
        "latitude": "1.3521",
        "longitude": "103.8198"
    },
    "bridge": {
        "name": "HOOBS - 031-45-154",
        "port": 51826,
        "pin": "031-45-154",
        "username": "XXXXX"
    },
    "description": "Controlling Panasonic CS-S9PKZW via Sensibo Sky; Dyson Pure Cool TP04; Panasonic TH-55EZ950S TV; Sony HT-Z9F Soundbar; SmartLife/Tuya Smart Plugs.",
    "ports": {},
    "accessories": [
        {
            "accessory": "receiver",
            "plugin_map": {
                "plugin_name": "homebridge-sony-audio-control",
                "index": 0
            },
            "name": "Bedroom Soundbar",
            "enableNetworkStandby": true,
            "inputs": {
                "accessory": "receiver",
                "name": "Bedroom Soundbar",
                "ip": "192.168.1.68",
                "enableNetworkStandby": true,
                "inputs": [
                    {
                        "name": "Apple TV",
                        "uri": "extInput:hdmi?port=1"
                    },
                    {
                        "name": "Unassigned",
                        "uri": "extInput:hdmi?port=2"
                    },
                    {
                        "name": "TV",
                        "uri": "extInput:tv"
                    },
                    {
                        "name": "USB Storage",
                        "uri": "storage:usb1"
                    },
                    {
                        "name": "Audio In",
                        "uri": "extInput:line"
                    },
                    {
                        "name": "Audio Network",
                        "uri": "netService:audio"
                    },
                    {
                        "name": "Multiroom Audio",
                        "uri": "multiroom:audio"
                    },
                    {
                        "name": "Chromecast Audio",
                        "uri": "cast:audio"
                    }
                ]
            },
            "ip": "192.168.1.68"
        }
    ],
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "username": "XXXXX",
            "password": "XXXXX",
            "countryCode": "SG",
            "devices": [
                {
                    "ipAddress": "192.168.1.64",
                    "serialNumber": "A2M-SG-MMA0424A",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true
                }
            ]
        },
        {
            "platform": "SensiboSky",
            "name": "SensiboSky",
            "apiKey": "XXXXX",
            "timeLapse": 5,
            "ai": false,
            "hideFan": false,
            "hideHumidity": false,
            "fixedState": "cool",
            "plugin_map": {
                "plugin_name": "homebridge-sensibo-sky-7modes"
            }
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "host": "192.168.1.67",
            "users": {
                "XXXXX": "XXXXX",
                "forceCt": true,
                "nativeHomeKitLights": true,
                "nativeHomeKitSensors": true,
                "nupnp": true,
                "resource": true
            },
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "hueDimmerRepeat": true,
            "hueMotionTemperatureHistory": true,
            "wallSwitch": true,
            "sensors": false,
            "forceEveWeather": true
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXXXX",
                "password": "XXXXX",
                "countryCode": "65",
                "platform": "smart_life",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "google-home",
            "plugin_map": {
                "plugin_name": "google-home"
            },
            "name": "Google Home",
            "debug": false,
            "token": "XXXXX"
        },
        {
            "platform": "PanasonicVieraTV",
            "tvs": [
                {
                    "ipAddress": "192.168.1.65",
                    "name": "Bedroom TV",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "Switch"
                        },
                        {
                            "id": "2",
                            "name": "Apple TV"
                        },
                        {
                            "id": "3",
                            "name": "Wii U"
                        },
                        {
                            "id": "4",
                            "name": "NES"
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-vieramatic"
            }
        }
    ]
}
```
If it helps, the following is in the console:
```
[Homebridge] [4/4/2020, 7:41:57 AM] Loaded config.json with 1 accessories and 6 platforms.
[Homebridge] [4/4/2020, 7:42:00 AM] Loaded plugin: "homebridge-dyson-pure-cool"
[Homebridge] [4/4/2020, 7:42:00 AM] Registering platform "homebridge-dyson-pure-cool.DysonPureCoolPlatform"
[Homebridge] [4/4/2020, 7:42:00 AM] Loaded plugin: "homebridge-sensibo-sky-7modes"
[Homebridge] [4/4/2020, 7:42:00 AM] Registering platform "homebridge-sensibo-sky-7modes.SensiboSky"
[Homebridge] [4/4/2020, 7:42:00 AM] Loaded plugin: "homebridge-sony-audio-control"
[Homebridge] [4/4/2020, 7:42:00 AM] Registering accessory "homebridge-sony-audio-control.receiver"
[Homebridge] [4/4/2020, 7:42:00 AM] Loaded plugin: "homebridge-tuya-web"
[Homebridge] [4/4/2020, 7:42:00 AM] Registering platform "homebridge-tuya-web.TuyaWebPlatform"
[Homebridge] [4/4/2020, 7:42:07 AM] Loaded plugin: "homebridge-vieramatic"
[Homebridge] homebridge API version: 2.4
[Homebridge] homebridge-vieramatic version: 0.9.7
[Homebridge] - Documentation: https://github.com/AntonioMeireles/homebridge-vieramatic#README
[Homebridge] - Bugs and feedback: https://github.com/AntonioMeireles/homebridge-vieramatic/issues
[Homebridge] [4/4/2020, 7:42:08 AM] Registering platform "homebridge-vieramatic.PanasonicVieraTV"
[Homebridge] [4/4/2020, 7:42:08 AM] Loaded plugin: "google-home"
[Homebridge] [4/4/2020, 7:42:08 AM] Registering platform "google-home.google-home"
[Homebridge] [4/4/2020, 7:42:13 AM] Loaded plugin: "hue"
[Homebridge] [4/4/2020, 7:42:13 AM] Registering platform "homebridge-hue.Hue"
[Homebridge] [4/4/2020, 7:42:13 AM] Loading 6 platforms...
[Homebridge] [4/4/2020, 7:42:13 AM] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [SensiboSky] Initializing SensiboSky platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [SensiboSky] Fetching Sensibo devices...
[Homebridge] [4/4/2020, 7:42:13 AM] [Hue] Initializing Hue platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [4/4/2020, 7:42:13 AM] [Hue] homebrige-hue v0.11.46, node v10.18.0, homebridge v0.4.50
[Homebridge] [4/4/2020, 7:42:13 AM] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [4/4/2020, 7:42:13 AM] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [Google Home] Initializing google-home platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[Homebridge] [4/4/2020, 7:42:13 AM] [PanasonicVieraTV] Vieramatic Init
[Homebridge] [4/4/2020, 7:42:13 AM] Loading 1 accessories...
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Initializing receiver accessory...
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating receiver services!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating information service!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating volume service!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating power service!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating input services!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating soundfield service Surround Mode!
[Homebridge] [4/4/2020, 7:42:13 AM] [Bedroom Soundbar] Creating soundfield service Stereo Mode!
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Nespresso] 708305853c71bf223d5d ead8ebd6-6859-4435-8203-1d0348542fd7
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Dining Power Strip] 70830585cc50e3561798 76c65158-735d-43de-932d-c1f8ab55421f
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Bedroom Power Strip] 70830585cc50e3561bb7 91a58318-01d7-435c-bfc1-7fd06af8c7dc
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Study Charge Point] 70830585cc50e3563f30 cb054346-1302-428d-9d62-7b7781e3bbbb
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Kitchen Charge Point] 708305853c71bf224075 10e56736-d923-4e3e-8338-3b699ecd03be
[Homebridge] [4/4/2020, 7:42:13 AM] [TuyaWebPlatform] Configuring cached accessory [Dining Charge Point] 70830585cc50e3561947 9d7db8a6-acff-4d67-9e58-ba6069b0b861
[Homebridge] [4/4/2020, 7:42:13 AM] [DysonPureCoolPlatform] Signing in.
[Homebridge] [4/4/2020, 7:42:14 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[Homebridge] [4/4/2020, 7:42:14 AM] API launched
[Homebridge] [4/4/2020, 7:42:16 AM] [PanasonicVieraTV] Ignoring TV (at '192.168.1.65') as it is unreachable. Likely to be powered off.
[Homebridge] [4/4/2020, 7:42:16 AM] [PanasonicVieraTV] DidFinishLaunching
[Homebridge] [4/4/2020, 7:42:16 AM] [Bedroom Soundbar] WebSocket client connected on endpoint ws://192.168.1.68:10000/sony/audio
[Homebridge] [4/4/2020, 7:42:16 AM] [Bedroom Soundbar] WebSocket client connected on endpoint ws://192.168.1.68:10000/sony/avContent
[Homebridge] [4/4/2020, 7:42:16 AM] [Bedroom Soundbar] Network standby is currently on
[Homebridge] [4/4/2020, 7:42:17 AM] [Google Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[Homebridge] [4/4/2020, 7:42:17 AM] [Hue] npm registry: status 404 Not Found
[Homebridge] [4/4/2020, 7:42:17 AM] [Hue] TypeError: username.replace is not a function
    at HuePlatform.maskUsernames (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:405:25)
    at request.then.catch.then (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:265:12)
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/home/hoobs/.hoobs/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Function.then (/home/hoobs/.hoobs/node_modules/deferred/_ext.js:70:4)
    at Deferred._settle (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/home/hoobs/.hoobs/node_modules/deferred/deferred.js:138:15)
    at Request.request [as _callback] (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:466:16)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Bedroom aircon : AI State:  false , RefreshCycle:  5000 , fixedState, AI, hideFan : cool false false
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] xqpToHg4 Setting fan up
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Device Added (Name: Bedroom aircon, ID: xqpToHg4, Group: pods)
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Study aircon : AI State:  false , RefreshCycle:  5500 , fixedState, AI, hideFan : cool false false
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] h2aNURkM Setting fan up
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Device Added (Name: Study aircon, ID: h2aNURkM, Group: pods)
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Initializing platform accessory "Bedroom aircon".
[Homebridge] [4/4/2020, 7:42:17 AM] [SensiboSky] Initializing platform accessory "Study aircon".
[Homebridge] [4/4/2020, 7:42:17 AM] Service is running on port 51826.
[Homebridge] [4/4/2020, 7:42:18 AM] [DysonPureCoolPlatform] Signed in.
[Homebridge] [4/4/2020, 7:42:19 AM] [DysonPureCoolPlatform] Got devices from the Dyson API.
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Bedroom Power Strip (switch / 70830585cc50e3561bb7)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Bedroom Power Strip] [70830585cc50e3561bb7] [91a58318-01d7-435c-bfc1-7fd06af8c7dc]
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Dining Power Strip (switch / 70830585cc50e3561798)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Dining Power Strip] [70830585cc50e3561798] [76c65158-735d-43de-932d-c1f8ab55421f]
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Study Charge Point (switch / 70830585cc50e3563f30)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Study Charge Point] [70830585cc50e3563f30] [cb054346-1302-428d-9d62-7b7781e3bbbb]
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Nespresso (switch / 708305853c71bf223d5d)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Nespresso] [708305853c71bf223d5d] [ead8ebd6-6859-4435-8203-1d0348542fd7]
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Kitchen Charge Point (switch / 708305853c71bf224075)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Kitchen Charge Point] [708305853c71bf224075] [10e56736-d923-4e3e-8338-3b699ecd03be]
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Adding: Dining Charge Point (switch / 70830585cc50e3561947)
[Homebridge] [4/4/2020, 7:42:21 AM] [TuyaWebPlatform] Existing Accessory found [Dining Charge Point] [70830585cc50e3561947] [9d7db8a6-acff-4d67-9e58-ba6069b0b861]
[Homebridge] [4/4/2020, 7:42:41 AM] [Google Home] Finished instance discovery
[Homebridge] [4/4/2020, 7:42:56 AM] [Google Home] Sending Sync Request
[Homebridge] [4/4/2020, 7:53:42 AM] [SensiboSky] Changed status (name: Study aircon, roomTemp: 28.5, on: false, mode: cool, targetTemp: 24, speed: high)
[Homebridge] [4/4/2020, 8:08:48 AM] [DysonPureCoolPlatform] A2M-SG-MMA0424A - set Active to 0: {"fpwr":"OFF","fmod":"OFF"}
[Homebridge] [4/4/2020, 8:08:50 AM] [SensiboSky] Changed status (name: Bedroom aircon, roomTemp: 29, on: true, mode: cool, targetTemp: 24, speed: low)```

**Comment by AntonioMeireles** [comment]
hi! 
Thanks for reporting.  some more questions in order to try to frame this issue...
- does the TV has a static IP (just checking) ?
- can you ping it ? (`ping 192.168.1.65`) . 
- TV is connected to net via wired network or wireless ?

Thanks in advance for your patience, and a great weekend!

**Comment by tetanus** [comment]
Hi Antonio,

Yes, the TV has a static IP of 192.168.1.65, which is set in my router using MAC address.
Yes, I can ping it. Returning results average 1.5ms.
The TV is connected via Wi-Fi.


T

**Comment by AntonioMeireles** [comment]
> Yes, the TV has a static IP of 192.168.1.65, which is set in my router using MAC address. Yes, I can ping it. Returning results average 1.5ms. The TV is connected via Wi-Fi.

could you plz run this command, if you have a chance ... `nmap -Pn 192.168.1.65 -p 55000 -sV` and  post here the output ? (this is *strange* :( )

**Comment by tetanus** [comment]
This is the output:

hoobs@hoobs:~ $ nmap -Pn 192.168.1.65 -p 55000 -sV
-bash: nmap: command not found

**Comment by AntonioMeireles** [comment]
@tetanus 

ok, thanks. (so `nmap` isn't installed ob your hoobs setup) . I just pushed a new release (**0.9.8**) that relaxes a bit the TV liveness test (increasing the connection timeout and retrying a few times in case of initial failure). This shouldn't hurt for the common case and may help on flaky / slow networks. This may or not fix your specific issue - Update to it and please report back if this changes anything. 


Thanks again for your patience, and a great weekend!

**Comment by tetanus** [comment]
After updating to 0.9.8, it would seem to have improved things because this is the output:

[Homebridge] homebridge-vieramatic version: 0.9.8
[Homebridge] - Documentation: https://github.com/AntonioMeireles/homebridge-vieramatic#README
[Homebridge] - Bugs and feedback: https://github.com/AntonioMeireles/homebridge-vieramatic/issues
[Homebridge] [4/7/2020, 2:38:35 AM] Registering platform "homebridge-vieramatic.PanasonicVieraTV"
[Homebridge] [4/7/2020, 2:38:41 AM] [PanasonicVieraTV] Vieramatic Init
[Homebridge] [4/7/2020, 2:38:41 AM] Loading 1 accessories...
[Homebridge] [4/7/2020, 2:38:44 AM] [PanasonicVieraTV] found a Panasonic VIErA TV (TH-55EZ950S) at 192.168.1.65 .
[Homebridge] [4/7/2020, 2:38:44 AM] [PanasonicVieraTV] DidFinishLaunching
[Homebridge] [4/7/2020, 2:38:44 AM] [TV] is running on port 39447.

However, my TV isn’t showing up in the Home app. I’m doing an uninstall/reinstall, and will report back soon.

**Comment by AntonioMeireles** [comment]
humm. do you have any chance of connecting the TV to your home network by cable, and then see if issues persist ?

**Comment by tetanus** [comment]
I hooked up to Ethernet, but the TV still does not appear in the Home app.

**Comment by AntonioMeireles** [comment]
@tetanus did by chance the new versions improved on this ?

thanks!

**Comment by tetanus** [comment]
Thank you for following up. I reinstalled the latest version, and while the log seems positive, the TV still doesn’t show up in the Home app.

5/14/2020, 11:39:53 PM [PanasonicVieraTV] Vieramatic Init
5/14/2020, 11:39:54 PM [PanasonicVieraTV] found a Panasonic VIErA TV (TH-55EZ950S) at 192.168.1.65 .
5/14/2020, 11:39:54 PM [PanasonicVieraTV] DidFinishLaunching
5/14/2020, 11:39:54 PM TV is running on port 36953.

**Comment by AntonioMeireles** [comment]
@tetanus 

(sorry lag) could you try removing homebridge from your Home and add it again, and check if the issue persists ?

thanks for your patience!

**Comment by tetanus** [comment]
Thanks for following up. I’m sorry, but I have way too many automations to lose if I remove Homebridge.

**Comment by AntonioMeireles** [comment]
@tetanus ok, understood. could you alternatively install the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) plugin ? does my plugin appear in its web ui ok ? 

thanks in advance

**Comment by tetanus** [comment]
Sorry for the late reply. 

I am running HOOBS. The Config UI X plugin does not appear in HOOB’s plugin search, so I’m not sure how to install the plugin.

**Comment by AntonioMeireles** [comment]
@tetanus, could you give a try to `2.0.0` ? still having issues on you setup ?

Thanks for your patience!

**Comment by tetanus** [comment]
Updated, but still nothing.

**Comment by tetanus** [comment]
This is with the latest update:

9/10/2020, 1:32:43 AM Loaded plugin "homebridge-vieramatic".
9/10/2020, 1:32:43 AM Loaded plugin "homebridge-tuya-web".
9/10/2020, 1:32:43 AM [smarthome-mijia] Mijia initialization skipped. Missing configuration data.
9/10/2020, 1:32:43 AM The requested platform "PanasonicVieraTV" was not registered by any plugin.
9/10/2020, 1:32:43 AM Your config.json is requesting the platform "PanasonicVieraTV" which has not been published by any installed plugins.

**Comment by AntonioMeireles** [comment]
humm... what that is telling us is that the plugin (`homebridge-vieramatic`) is not installed at all. you need to install it via hoobs UI. after that you may still get an error **but** not definitivelly that one :-)

**Comment by AntonioMeireles** [comment]
can you post you full hb configs.json and the full homebridge logs? this error is **interesting** and totally different from anything else before it.

**Comment by AntonioMeireles** [comment]
> can you post you full hb `config.json` and the full homebridge logs? this error is **interesting** and totally different from anything else before it.

or is it still same as in Apr 4 ?

**Comment by tetanus** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 3,
        "home_setup_id": "X-HM://00252UEC2FF6K",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 60,
        "theme": "hoobs-dark",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "SG",
        "postal_code": "390999",
        "latitude": "1.3521",
        "longitude": "103.8198"
    },
    "bridge": {
        "name": "HOOBS - 031-45-154",
        "port": 51826,
        "pin": "XXXX",
        "username": "XXXX"
    },
    "description": "Controlling Panasonic CS-S9PKZW via Sensibo Air; Dyson Pure Cool TP04; Panasonic TH-55EZ950S TV; Sony HT-Z9F Soundbar; Tuya SmartLife Smart Plugs; Tuya RF Hub; Tuya IR Hub; Aqara N100 Smart Door Lock.",
    "ports": {},
    "accessories": [
        {
            "accessory": "receiver",
            "plugin_map": {
                "plugin_name": "homebridge-sony-audio-control",
                "index": 0
            },
            "name": "Bedroom Soundbar",
            "enableNetworkStandby": true,
            "inputs": {
                "accessory": "receiver",
                "name": "Bedroom Soundbar",
                "ip": "192.168.1.68",
                "enableNetworkStandby": true,
                "inputs": [
                    {
                        "name": "Apple TV",
                        "uri": "extInput:hdmi?port=1"
                    },
                    {
                        "name": "Unassigned",
                        "uri": "extInput:hdmi?port=2"
                    },
                    {
                        "name": "TV",
                        "uri": "extInput:tv"
                    },
                    {
                        "name": "USB Storage",
                        "uri": "storage:usb1"
                    },
                    {
                        "name": "Audio In",
                        "uri": "extInput:line"
                    },
                    {
                        "name": "Audio Network",
                        "uri": "netService:audio"
                    },
                    {
                        "name": "Multiroom Audio",
                        "uri": "multiroom:audio"
                    },
                    {
                        "name": "Chromecast Audio",
                        "uri": "cast:audio"
                    }
                ]
            },
            "ip": "192.168.1.68",
            "outputZone": "extOutput:zone?zone=1"
        },
        {
            "accessory": "DummySwitch",
            "plugin_map": {
                "plugin_name": "homebridge-dummy",
                "index": 0
            },
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "name": "Dummy Door Lock"
        }
    ],
    "platforms": [
        {
            "platform": "DysonPureCoolPlatform",
            "username": "XXXX",
            "password": "XXXX",
            "countryCode": "SG",
            "devices": [
                {
                    "ipAddress": "192.168.1.64",
                    "serialNumber": "XXXX",
                    "enableAutoModeWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": false,
                    "isAirQualitySensorEnabled": true
                }
            ]
        },
        {
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Home",
            "debug": false,
            "token": "XXXX",
            "notice": "Keep your token a secret!",
            "forceFahrenheit": false
        },
        {
            "platform": "SensiboAC",
            "apiKey": "XXXX",
            "disableFan": true,
            "disableDry": false,
            "enableSyncButton": true,
            "debug": false,
            "plugin_map": {
                "plugin_name": "homebridge-sensibo-ac"
            },
            "enableOccupancySensor": true,
            "enableClimateReactSwitch": true,
            "enableHistoryStorage": true,
            "externalHumiditySensor": true
        },
        {
            "platform": "TuyaWebPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            },
            "name": "TuyaWebPlatform",
            "scenes": false,
            "options": {
                "platform": "smart_life",
                "username": "XXXX",
                "password": "XXXX",
                "countryCode": "65",
                "pollingInterval": 300
            }
        },
        {
            "platform": "smarthome-mijia",
            "plugin_map": {
                "plugin_name": "homebridge-smarthome-plus"
            },
        {
            "platform": "PanasonicVieraTV",
            "plugin_map": {
                "plugin_name": "homebridge-vieramatic"
            },
            "tvs": {
                "platform": "PanasonicVieraTV",
                "tvs": [
                    {
                        "ipAddress": "192.168.1.65",
                        "name": "Bedroom TV",
                        "hdmiInputs": [
                            {
                                "id": "1",
                                "name": "Switch"
                            },
                            {
                                "id": "2",
                                "name": "Apple TV"
                            },
                            {
                                "id": "3",
                                "name": "Wii U"
                            },
                            {
                                "id": "4",
                                "name": "NES"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

**Comment by tetanus** [comment]
FYI, this plugin works fine for me: https://github.com/g30r93g/homebridge-panasonic#readme.

**Comment by tetanus** [comment]
I did a factory reset of HOOBS and removed Homebridge from HomeKit. Re-adding HOOBS and reinstalling your plugin, I get this in the log:

9/10/2020, 4:22:55 PM 
> fast-xml-parser@3.17.4 postinstall /home/hoobs/.hoobs/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0
9/10/2020, 4:22:56 PM [96m[1mLove fast-xml-parser? Check [32mhttps://amitkumargupta.work [96m[1mfor more projects and contribution.[0m
9/10/2020, 4:22:56 PM npm
9/10/2020, 4:22:56 PM  notice created a lockfile as package-lock.json. You should commit this file.
9/10/2020, 4:22:56 PM npm
9/10/2020, 4:22:56 PM  WARN eslint-plugin-simple-import-sort@5.0.3 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
9/10/2020, 4:22:56 PM + homebridge-vieramatic@2.0.2
added 20 packages from 23 contributors in 5.262s
9/10/2020, 4:22:56 PM 
1 package is looking for funding
  run `npm fund` for details
9/10/2020, 4:22:56 PM Plugin "homebridge-vieramatic" installed.
9/10/2020, 4:22:58 PM Got SIGINT, shutting down Bridge...
9/10/2020, 4:23:04 PM Loaded plugin "homebridge-vieramatic".
9/10/2020, 4:23:04 PM The requested platform "PanasonicVieraTV" was not registered by any plugin.
9/10/2020, 4:23:04 PM Your config.json is requesting the platform "PanasonicVieraTV" which has not been published by any installed plugins.
9/10/2020, 4:23:04 PM Bridge is running on port 51826.
9/10/2020, 4:23:28 PM Got SIGINT, shutting down Bridge...
9/10/2020, 4:23:34 PM Loaded plugin "homebridge-vieramatic".
9/10/2020, 4:23:34 PM The requested platform "PanasonicVieraTV" was not registered by any plugin.
9/10/2020, 4:23:34 PM Your config.json is requesting the platform "PanasonicVieraTV" which has not been published by any installed plugins.
9/10/2020, 4:23:34 PM Bridge is running on port 51826.

**Comment by AntonioMeireles** [comment]
@tetanus 

FWIW, at sight and right now this seems to be a 100% hoobs specific issue :( . could you try to follow the "Installing Plugins Manually" [from the HOOBS docs](https://support.hoobs.org/docs/5e763b63e87d1e02b6c19d2b) and see if that makes a difference?

**Comment by tetanus** [comment]
Yeah, in fact the last round of reinstalling, I followed the HOOB instructions to install, but still no dice.

**Comment by ValoV83** [comment]
I'd really like to see full HOOBS support added as well. George Nick Gorzynski (g30r93g) who wrote and developed the Homebridge-Panasonic plugin - https://github.com/g30r93g/homebridge-panasonic has decided to stop developing his plugin - https://github.com/g30r93g/homebridge-panasonic/issues/43#issuecomment-725677057

I'm a HOOBS user and would lie to switch over to this plugin to get full iOS 14 support which was a problem with g30r93g's Homebridge-Panasonic plugin: https://github.com/g30r93g/homebridge-panasonic/issues/43

**Comment by AntonioMeireles** [comment]
@g30r93g 

could you please, if you find some spare time, take a look at this to check what would be the remaining missing bits ? 

António

**Comment by ValoV83** [comment]
> I'd really like to see full HOOBS support added as well. George Nick Gorzynski (g30r93g) who wrote and developed the Homebridge-Panasonic plugin - https://github.com/g30r93g/homebridge-panasonic has decided to stop developing his plugin - [g30r93g/homebridge-panasonic#43 (comment)](https://github.com/g30r93g/homebridge-panasonic/issues/43#issuecomment-725677057)
> 
> I'm a HOOBS user and would lie to switch over to this plugin to get full iOS 14 support which was a problem with g30r93g's Homebridge-Panasonic plugin: [g30r93g/homebridge-panasonic#43](https://github.com/g30r93g/homebridge-panasonic/issues/43)

With @g30r93g stopping development of his plugin. I've switched over to Homebridge from HOOBS and I'm now using Homebridge-Vieramatic without any problems.

**Comment by BukriChod** [comment]
> I'd really like to see full HOOBS support added as well. George Nick Gorzynski (g30r93g) who wrote and developed the Homebridge-Panasonic plugin - https://github.com/g30r93g/homebridge-panasonic has decided to stop developing his plugin - [g30r93g/homebridge-panasonic#43 (comment)](https://github.com/g30r93g/homebridge-panasonic/issues/43#issuecomment-725677057)
> 
> I'm a HOOBS user and would lie to switch over to this plugin to get full iOS 14 support which was a problem with g30r93g's Homebridge-Panasonic plugin: [g30r93g/homebridge-panasonic#43](https://github.com/g30r93g/homebridge-panasonic/issues/43)

Hi @AntonioMeireles is there any updates or plans to support Hoobs? I’m having difficulties getting it to work (similar to above trail). Just trying to manage my own expectations on whether I should persist with trying to find workarounds or give up and shift my entire config over from Hoobs to Homebridge UX again. Thanks for all your great work so far.

**Comment by ValoV83** [comment]
> > I'd really like to see full HOOBS support added as well. George Nick Gorzynski (g30r93g) who wrote and developed the Homebridge-Panasonic plugin - https://github.com/g30r93g/homebridge-panasonic has decided to stop developing his plugin - [g30r93g/homebridge-panasonic#43 (comment)](https://github.com/g30r93g/homebridge-panasonic/issues/43#issuecomment-725677057)
> > I'm a HOOBS user and would lie to switch over to this plugin to get full iOS 14 support which was a problem with g30r93g's Homebridge-Panasonic plugin: [g30r93g/homebridge-panasonic#43](https://github.com/g30r93g/homebridge-panasonic/issues/43)
> 
> Hi @AntonioMeireles is there any updates or plans to support Hoobs? I’m having difficulties getting it to work (similar to above trail). Just trying to manage my own expectations on whether I should persist with trying to find workarounds or give up and shift my entire config over from Hoobs to Homebridge UX again. Thanks for all your great work so far.

I was having other issues with HOOBS as well as the issue with my Panasonic TV working with iOS 14. I used this guide to backup my HOOBS data and move over to Homebridge. It took me just under 1hr and It's been the best decision I've made as my HOOBS issue have been resolved and my devices running on Homebridge have been rock solid.

I'm also now using Homebridge-Vieramatic without any problems to control my Panasonic TV.

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge

**Comment by AntonioMeireles** [comment]
@BukriChod 

HOOBS support is pending someone to step in and ensure it as i'm not an HOOBS user nor have time / resources to support HOOBS (which is something i personally have an use case for).  As soon as a brave soul tackles it i'll in a PR i'll merge it in a bit :-) 

Thanks for your understanding and an Happy 2021!

**Comment by BukriChod** [comment]
Thanks @AntonioMeireles appreciate the response and the work done so far... will take @ValoV83 recommendation and migrate to Homebridge tomorrow. Here’s hoping it goes smoothly. Happy New Year!!

**Comment by AntonioMeireles** [comment]
fwiw, [success](https://github.com/AntonioMeireles/homebridge-vieramatic/issues/57) running this plugin on top of HOOBS in https://github.com/AntonioMeireles/homebridge-vieramatic/issues/57#issuecomment-760274959. Now, if some regular HOOBS user volunteered to write a proper guide to update the Docs...

**Comment by AntonioMeireles** [comment]
per feedback in #85, and from `homebridge-vieramatic@3.2.3`HOOBS is supposed to be supported out of the box, so **closing**. 

please reopen if there are any remaining issue. 

All the Best, 

António
