### ISSUE TITLE
Homebridge Beta - Warning and Error

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#64]
**Describe your issue**
Warning and error in the logs when using HB Beta 1.3.0 - Beta 49
**Issue Context**
The pluging is working, it's just a post to let you prepare for the next version if necessary.

Please add the following items, when applicable:

1. the homebridge logs, up from starting until the bug popped up there. 

[03/02/2021, 09:26:10] The plugin 'homebridge-vieramatic' slows down requests made to homebridge! The read handler for the characteristic 'Active' was slow to respond!
[03/02/2021, 09:26:10] The plugin 'homebridge-vieramatic' slows down requests made to homebridge! The read handler for the characteristic 'Mute' was slow to respond!

2. Details about your specific homebridge setup
    - Raspberry 3+
    - Raspbian GNU/Linux Buster (10)
    - v14.15.4
    - 1.3.0 - Beta 49
    - Last official release

Best regards,

Alexis

**Comment by AntonioMeireles** [comment]
@Seexelas  

FWIW i'm not yet targeting 1.3.x betas in the plugin (albeit also running them) until 1.3.0 is actually out. I've also seens that error (should be harmless) but only when **not** running the default **bonjour-hap** backend i.e only when using **ciao** as the mDNS Advertiser Library.  (vd https://github.com/homebridge/homebridge/issues/2765). which one are you running on your setup ? 

thanks in advance!

**Comment by Marfre888** [comment]
@AntonioMeireles I came here to report this exact thing..

Can confirm that the error is produced when ciao is used and not when bonjour-hap is used. 

Thanks

**Comment by AntonioMeireles** [comment]
@Marfre888 

Hi again && thanks for confirming it. will dig :-)

**Comment by Marfre888** [comment]
Hi :)

Seems fairly harmless from my experience. I have it set to a child bridge and that seems to be working correctly.

This is my error, if it helps point you in the right direction. What it feels like to me is that they have tightened the timeout tolerances so now it spits out this error quicker. I've had other plugins doing it intermittently too.

![vieramatic](https://user-images.githubusercontent.com/63603736/108065350-28e0f400-705e-11eb-957f-92c9897a845c.PNG)

**Comment by AntonioMeireles** [comment]
@Marfre888 

hi, 

give a try please, when you have time, to latest `homebridge-vieramatic@3.0.1`.  should had made most if not all the warning go away. If not, please post here the ones you're getting. 

Thanks in advance and have a great weekend!

**Comment by WummoFTW** [comment]
Hello, I'm running Homebridge V1.3.0 and Vieramatic plugin on version V3.0.1 version and I'm still getting the same error

Error message:
_[21/02/2021, 01:35:33] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[21/02/2021, 01:35:34] [PanasonicVieraTV] (getVolume) unable to get volume from TV...
[21/02/2021, 01:35:37] [PanasonicVieraTV] (getVolume) unable to get volume from TV..._

**Comment by AntonioMeireles** [comment]
@WummoFTW 

many thanks for reporting! But things still work, sanely right ? also, using _ciao_ mdns backend  ?  could you tell us more about your homebridge setup ? [trying to spot a pattern to get rid of the warnings in all fronts]. 

thanks in advance and have a great weekend!

**Comment by AntonioMeireles** [comment]
@WummoFTW

btw - the warnings are now only about the `characteristic 'Active' ` ?

**Comment by Marfre888** [comment]
> @WummoFTW
> 
> btw - the warnings are now only about the `characteristic 'Active' ` ?

Same here.. only about Active

The problem seems to only pop up if my TV is off. The plugin insists on getting TV volume, otherwise seems to be working correctly. Will try to enable Ciao and report back


--------

[2/21/2021 14:50:25] [homebridge-vieramatic] WARNING: unable to fetch specs from TV at '192.168.1.14'. Using the previously cached ones: 

{
  friendlyName: 'Upstairs Living Room Television',
  manufacturer: 'Panasonic',
  modelName: 'Panasonic VIErA',
  modelNumber: 'TX-47AS650E',
  requiresEncryption: false,
  serialNumber: '4D454930-0200-1000-8001-20C6EBE0422D'
}
[2/21/2021 14:50:25] [homebridge-vieramatic] successfully loaded Upstairs Living Room Television
Preparing Advertiser for 'Upstairs Living Room Television B40B' using bonjour-hap backend!
Starting to advertise 'Upstairs Living Room Television B40B' using bonjour-hap backend!
[2/21/2021 14:50:25] Upstairs Living Room Television B40B is running on port 37763.
[2/21/2021 14:50:25] Please add [Upstairs Living Room Television B40B] manually in Home app. Setup Code: 026-04-094
[2/21/2021 14:50:28] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:29] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[2/21/2021 14:50:31] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:34] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:40] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:43] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:50] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:56] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:50:59] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:05] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:08] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:14] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:21] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:24] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:30] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:51:33] [homebridge-vieramatic] (getVolume) unable to get volume from TV...


------

**Comment by Marfre888** [comment]
With Ciao enabled..

[2/21/2021 14:53:28] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://git.io/JtMGR for more info.
[2/21/2021 14:53:28] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Mute' was slow to respond! See https://git.io/JtMGR for more info.
[2/21/2021 14:53:28] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Volume' was slow to respond! See https://git.io/JtMGR for more info.
[2/21/2021 14:53:28] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:31] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:31] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:37] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:40] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:47] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:53] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:53:56] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:54:02] [homebridge-vieramatic] (getVolume) unable to get volume from TV...
[2/21/2021 14:54:05] [homebridge-vieramatic] (getVolume) unable to get volume from TV...

**Comment by AntonioMeireles** [comment]
@Marfre888 @WummoFTW

Thanks both!

humm... so **this is only an issue now if and when the TV is down**. makes more sense now. will see what i can do...

**Comment by Marfre888** [comment]
Will do some more testing cause I only had time to do some quick runs, but it’s looking like that to me yes

**Comment by Marfre888** [comment]
Yeah, it seems the problem now is only with ‘Active’

However I’m getting spammed with ‘unable to get volume from TV’ which only happened once after the plugin was restarted before yesterday’s update. Note: This only happens when the TV is off from the wall.

**Comment by AntonioMeireles** [comment]
> However I’m getting spammed with ‘unable to get volume from TV’ which only happened once after the plugin was restarted before yesterday’s update. Note: This only happens when the TV is off from the wall.

i do expect to have a fix for this later today. thanks you all for your patience and great feedback!

**Comment by Marfre888** [comment]
> > However I’m getting spammed with ‘unable to get volume from TV’ which only happened once after the plugin was restarted before yesterday’s update. Note: This only happens when the TV is off from the wall.
> 
> i do expect to have a fix for this later today. thanks you all for your patience and great feedback!

Thanks, I just opened the logs to see is everything was working well after the big update, and the logs only had '‘unable to get volume from TV' in it, about 1 every 5sec or so.. I've gone back down to 2.0.26, as it seems the problem started with update 3.0

**Comment by AntonioMeireles** [comment]
it should be harmless, fwiw.

**Comment by AntonioMeireles** [comment]
could you all give a try to `homebridge-vieramatic@3.0.3` that i've just got published ?

it should get us all rid of the `(getVolume) unable to get volume from TV...` spam. 

thanks in advance!

**Comment by Dreiviertelblut** [comment]
The entries (getVolume) in the log every 5 Seconds is solved with V3.0.3. Many thanks for the quick support.

Nevertheless, everytime, when opening Homebridge gui (homebridge-config-ui-x) or by doing some actions with it, the entry with the getVolume is there again.
Note:  I have not configured Volume of my TV to show up in Homekit, as I don't need it. But it is shown as seperate device in homebridge gui. Is that intended? Just a thought, as it is creating log entries without reason now....

**Comment by AntonioMeireles** [comment]
@Dreiviertelblut 

`homebridge-vieramatic@3.0.4` is just out and reduces noise level a bit more. check plz if it is enough 😄

**Comment by Dreiviertelblut** [comment]
Yes, that did the trick. Many thanks. :-)

**Comment by Marfre888** [comment]
> @Dreiviertelblut
> 
> `homebridge-vieramatic@3.0.4` is just out and reduces noise level a bit more. check plz if it is enough 😄

Works great,

Thank you so much for fixing it so promptly.

**Comment by AntonioMeireles** [comment]
folks, 

anyone still getting `The plugin 'homebridge-vieramatic' slows down requests made to homebridge!` spam in the logs with latest version ? (with either of the mdns backends ?) 

thanks in advance!

**Comment by Seexelas** [comment]
Ok for me too ! Thx a lot

**Comment by AntonioMeireles** [comment]
@Seexelas,  

so ok to close ?

&& **thanks you all**

**Comment by Seexelas** [comment]
Ok to close :)
