### ISSUE TITLE
IGNORING '192.168.0.2' as it is not reachable, and we can't relay on cached data as it seems that it was never ever seen and setup before.   Please make sure that your TV is powered ON and connected to the network.

### ISSUE THREAD

**Issue by matheushabitz** [AntonioMeireles/homebridge-vieramatic#71]
> `IGNORING '192.168.0.2' as it is not reachable, and we can't relay on cached data as it seems that it was never ever seen and setup before.`

 Please make sure that your TV is powered ON and connected to the network.

#### **Issue Context**

Please add the following items, when applicable:

1. the homebridge logs, up from starting until the bug popped up there.
2. your homebridge's `config.json` contents.

```json
 "tvs": [
                {
                    "friendlyName": "TV Sala",
                    "ipAddress": "192.168.0.100",
                    "disabledAppSupport": true,
                    "customVolumeSlider": true
                }
            ],
            "platform": "PanasonicVieraTV"
        }
    ]
}
```
3. the contents of `accessories/vieramatic.json` (path is relative to homebridge's _datadir_)
4. Details about your specific homebridge setup
    - hardware and arch
    - Operating System and its version - Windows 10 Pro 64bits
    - NodeJS version- v14.15.5
    - Homebridge version - v1.3.2
    - specific vieramatic version being used - v3.1.4
    - Viera TV(s) model(s) being used (and connectivity type being used - wired or wireless) - Panasonic Viera PCTV000144=B576894E80DE7B83EB37 -  wired
5. anything else you may find relevant
Normally connects normally with the Panasonic TV Remote 3

**Comment by AntonioMeireles** [comment]
Hi, 

so, some questions to try to sort this out: 

- this is a first setup, right ? i.e. never worked before with any previous plugin version, right ?
- the TV is pingable from the windows host ? (and from within the homebridge VM ?) 
- you're using hyper-v right ?
- could you attach the full homebridge logs ?

thanks in advance!

**Comment by Marfre888** [comment]
Hi @AntonioMeireles a recent update just broke this, as I have this same problem, but works correctly as of 3.1.0, will figure out which version did it

**Comment by Marfre888** [comment]
No, I have this exact problem.. problem started as of 3.1.3

**Comment by AntonioMeireles** [comment]
@Marfre888 

TV model/specs and vieramatic.json and homebridge config contents plz. 


OTOH ... 
> Last week I changed IP for this TV and this plugin refused to locate it at the new IP (....) 

This may or not be expected... *if* you change TV's IP you **then** need to **also** change TV's IP on homebridge's config.json **and** **either** resetup TV **or** edit manually `vieramatic.json` to update the  IP address. If this doesn't fix it would need logs / more data ...

**Comment by Marfre888** [comment]
> @Marfre888
> 
> TV model/specs and vieramatic.json and homebridge config contents plz.
> 
> OTOH ...
> 
> > Last week I changed IP for this TV and this plugin refused to locate it at the new IP (....)
> 
> This may or not be expected... _if_ you change TV's IP you **then** need to **also** change TV's IP on homebridge's config.json **and** **either** resetup TV **or** edit manually `vieramatic.json` to update the IP address. If this doesn't fix it would need logs / more data ...

@AntonioMeireles 

1. Coming up

2. Yes, I did all that and it still wouldn't find it, downgrading firmware fixed whatever bug it was, and now it continues to work after upgrading again

**Comment by Marfre888** [comment]
friendlyName: 'Upstairs Living Room Television',
  manufacturer: 'Panasonic',
  modelName: 'Panasonic VIErA',
  modelNumber: 'TX-47AS650E',
  requiresEncryption: false,
  serialNumber: 'xxxx'

`{
            "tvs": [
                {
                    "friendlyName": "Upstairs Living Room Television",
                    "ipAddress": "192.168.1.xx",
                    "mac": "xx:xx:xx:xx:xx:xx

",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "STB"
                        },
                        {
                            "id": "3",
                            "name": "Blu-ray Disc"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV",
            "_bridge": {
                "username": "xx:xx:xx:xx:xx:xx",
                "port": xxxxx
            }
        }`


[vieramatic.json.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/6115265/vieramatic.json.txt)

**Comment by AntonioMeireles** [comment]
@Marfre888 

just give a try to just published `homebridge-vieramatic@3.1.6` and report back. should fix it (if i'm right)

**Comment by Marfre888** [comment]
> @Marfre888
> 
> just give a try to just published `homebridge-vieramatic@3.1.6` and report back. should fix it (if i'm right)

You are correct :)

Thank you for that

Sidenote: Is it intended behavior that this plugin isn't exposed through the child bridge but as a separate accessory that bypasses the child bridge? ie; It will still appear in the 'add accessory' page before the child bridge is added to homekit

**Comment by AntonioMeireles** [comment]
> You are correct :)
> 

**WooT**! Thanks for confirming! @matheushabitz could you test it too and see if it solves your issue too please ?

> Sidenote: Is it intended behavior that this plugin isn't exposed through the child bridge but as a separate accessory that bypasses the child bridge? ie; It will still appear in the 'add accessory' page before the child bridge is added to homekit

This is a platform plugin i.e. it can have/managed multiple attached accessories itself (several TVs).  AFAIK this kind of plugins are not currently supported under _child bridges_, per [here](https://github.com/homebridge/homebridge/wiki/Child-Bridges#multiple-accessories-on-the-same-child-bridge).

Thanks once again!

**Comment by Marfre888** [comment]
>> This is a platform plugin i.e. it can have/managed multiple attached accessories itself (several TVs). AFAIK this kind of plugins are not currently supported under _child bridges_, per [here](https://github.com/homebridge/homebridge/wiki/Child-Bridges#multiple-accessories-on-the-same-child-bridge).
> 
> Thanks once again!

Ahh right, stupid me.

It lets me add it as a child bridge, which is handy in case I want to restart this specific plugin, but that explains why I won't automatically add through the child bridge.

Thanks @AntonioMeireles

**Comment by AntonioMeireles** [comment]
@matheushabitz 

any updates on this ? i.e. does currently shipping version fixed it ? 

thanks in advance and have a great weekend!

**Comment by matheushabitz** [comment]
> @matheushabitz
> 
> any updates on this ? i.e. does currently shipping version fixed it ?
> 
> thanks in advance and have a great weekend!

@AntonioMeireles 

Good Morning!

Problem solved. It's working 100%!

Thank you so much!

**Comment by AntonioMeireles** [comment]
@matheushabitz 

great to hear! thanks all! 

will close.
