### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by bsoener** [AntonioMeireles/homebridge-vieramatic#90]
I have a problem this plugin. My homebridge crashes unfortunately. Anyone have an idea what this can be?

```
[17/01/2022, 15:47:49] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[17/01/2022, 15:47:49] [PanasonicVieraTV] Using the previously cached ones:

 {"friendlyName":"Viera ","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBC536E5"}
[17/01/2022, 15:47:52] AssertionError [ERR_ASSERTION]: Accessories must be created with a valid UUID.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:418:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at Ae.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:131:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ae.discoverDevices (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:67:23)
    at HomebridgeAPI.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:39:7)
[17/01/2022, 15:47:52] Got SIGTERM, shutting down Homebridge...
```

```
 {
            "tvs": [
                {
                    "friendlyName": "Viera ",
                    "ipAddress": "192.168.178.115",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "Denon"
                        },
                        {
                            "id": "2",
                            "name": "PS5"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": true
                }
            ],
            "platform": "PanasonicVieraTV"
        },
```

**Comment by AntonioMeireles** [comment]
Hi, 

thanks for reporting ...

need way more data ... a) exact plugin version, node version/arch, homebridge version ...

also, please add the output of `curl -Lsk http://192.168.178.115:55000/nrc/ddd.xml`. 

Your TV is a bit on the older side... were working with previous versions of the plugin  (if so, until which one ?) or are you trying the plugin for the first time ?

Thanks in advance!

António

**Comment by AntonioMeireles** [comment]
FWIW, this error is way, way weird...

it's complaining that your TVs S/N which we (the plugin)  reuse as an UUID for Homekit/Homebridge purposes is not valid (it is!). looking into it.

**Comment by bsoener** [comment]
So I installed this plugin a month ago and it worked great. Do not know what the reason can be.
-Node.js version v16.13.2 
-Npm version v8.1.2 
-Homebridge v1.3.9  

How do I open this vieramatic.json?

**Comment by AntonioMeireles** [comment]
`vieramatic.json` is relative to the dir where it is homebridge's  config.json (inside `accessories` subdir)

**Comment by bsoener** [comment]
`{"4D454930-0200-1000-8001-20C6EBC3C18D":{"data":{"inputs":{"applications":{"0":{"id":"0387878700000016","name":"VIERA Link"},"1":{"id":"0010000200000001","name":"Netflix"},"2":{"id":"0387878700000014","name":"Media Server"},"3":{"id":"0077777700000002","name":"Web Browser"},"4":{"id":"0387878700000009","name":"Haupt-Menü"},"5":{"id":"0387878700000003","name":"TV Guide"},"6":{"id":"0387878700000001","name":"TV"},"7":{"id":"0387878700000013","name":"TV-Aufnahmen"},"8":{"id":"0387878700000050","name":"Multi Window"},"9":{"id":"0387878700000049","name":"Spiegelung"},"10":{"id":"0070000200000001","name":"YouTube"},"11":{"id":"0020007100000001","name":"Meteonews TV"},"12":{"id":"0020003E00000001","name":"3doo Player for Panasonic Viera TV"},"13":{"id":"0020000600000001","name":"ARTE"},"14":{"id":"0020000300000001","name":"tagesschau"},"15":{"id":"0387878700000032","name":"Media Player"},"16":{"id":"0070001000000001","name":"PlayJam"}},"hdmi":[{"id":"1","name":"Denon"},{"id":"2","name":"PS5"}],"TUNER":{"hidden":0}},"ipAddress":"192.168.178.115","specs":{"friendlyName":"Viera ","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBC3C18D"}}}}`

**Comment by AntonioMeireles** [comment]
@bsoener 

can you please give a try to `homebridge-vieramatic@4.0.9` ? does it change anything ?

thanks in advance!

**Comment by bsoener** [comment]
```
[17/01/2022, 16:46:21] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[17/01/2022, 16:46:21] [PanasonicVieraTV] Using the previously cached ones:

 {"friendlyName":"Viera ","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-xxxxxxxxxx"}
[17/01/2022, 16:46:25] AssertionError [ERR_ASSERTION]: Accessories must be created with a valid UUID.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:418:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at Ae.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:131:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ae.discoverDevices (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:67:23)
    at HomebridgeAPI.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:39:7)
[17/01/2022, 16:46:25] Got SIGTERM, shutting down Homebridge...
```
did update. still same problem..

**Comment by AntonioMeireles** [comment]
puzzled. can you please delete (or rename) the `vieramatic.json` file, and restart homebridge ? (but now with the TV turned ON) ?

**Comment by bsoener** [comment]
vieramatic.json deleted, Tv turned on, Homebridge restarted and it works again. Thank you Perfect

**Comment by AntonioMeireles** [comment]
**GREAT to hear**. something odd may have happened. will close as things work for your again. will keep an eye on it anyway. 

just bug me again if new issues arise. 

all the best, 

António

**Comment by bsoener** [comment]
```
[18/01/2022, 16:49:33] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[18/01/2022, 16:49:33] [PanasonicVieraTV] Using the previously cached ones:

 {"friendlyName":"Viera","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBC3C18D"}
[18/01/2022, 16:49:37] AssertionError [ERR_ASSERTION]: Accessories must be created with a valid UUID.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:418:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at Ae.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:131:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ae.discoverDevices (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:67:23)
    at HomebridgeAPI.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:39:7)
[18/01/2022, 16:49:37] Got SIGTERM, shutting down Homebridge...

```
Hi. Error has appeared again. Must deactivate the plugin again. What could be the reason?

**Comment by bsoener** [comment]
I will try it later. Let me know then

**Comment by tjm7844** [comment]
I also have noticed this issue (I have a ZT60, so roughly same generation as @bsoener.

I've been using the plugin for at least a year with few/no issues, but noticed something a couple of days ago (maybe Saturday/Sunday, but I'm not positive): I wasn't getting the error mentioned here, and the TV would turn on using the Home App, but the tile would immediately flip to "off" (the TV would still stay on). I then couldn't turn off the TV through Home (had to use the standard IR remote).

I tried installing the 1.4.0 homebridge beta last night, and started getting this error, with homebridge crashing on loop. Played around with it for an hour or so, couldn't fix it (even after rolling back to 1.3.9 ), so went to bed. When I woke up this morning and checked again, the crashing (UUID) error had stopped.

I have since moved this plugin over to a child bridge (as I have a couple other slowish plugins anyway, so thought I might handle them all), and after restarting Homebridge, have started getting this error again. However, at least because it's on a Child Bridge, it's not crashing my entire Homebridge instance, only this plugin's process.

I went through the steps you listed above, and here were my results:

Existing/Original vieramatic.json:
`{"4D454930-0200-1000-8001-8CC121609620":{"data":{"inputs":{"hdmi":[{"id":"2","name":"Receiver","hidden":0}],"applications":{"0":{"name":"Media player","id":"0387878700000032","hidden":1},"1":{"name":"DLNA server","id":"0387878700000014","hidden":1},"2":{"name":"VIERA Link","id":"0387878700000016","hidden":1},"3":{"name":"TV","id":"0387878700000001","hidden":1},"4":{"name":"Menu","id":"0387878700000009","hidden":1},"5":{"name":"Web Browser","id":"0077777700000002","hidden":1},"6":{"name":"Paint","id":"0387878700000026","hidden":1},"7":{"name":"Put Three","id":"0387878700000036","hidden":1},"8":{"name":"Family Reversi","id":"0387878700000037","hidden":1},"9":{"name":"Touch Connect","id":"0387878700000038","hidden":1},"10":{"name":"Mirroring","id":"0387878700000049","hidden":1},"11":{"name":"Netflix","id":"0010000200000001","hidden":0},"12":{"name":"YouTube","id":"0070000200000001","hidden":1},"13":{"name":"HSN Shop by Remote","id":"0010002000000001","hidden":1},"14":{"name":"CinemaNow","id":"0010000300000001","hidden":1},"15":{"name":"PlayJam","id":"0070001000000001","hidden":1},"16":{"name":"Xumo","id":"0310005700000001","hidden":1},"17":{"name":"VUDU HD Movies","id":"0010001300000001","hidden":1},"18":{"name":"Jotter","id":"0387878700000022","hidden":1},"19":{"name":"Classical Archives Player","id":"0070001700000001","hidden":1}},"TUNER":{"hidden":0}},"specs":{"friendlyName":"Living Room Panasonic","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"ZT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-8CC121609620"},"ipAddress":"192.168.1.155"}}}`

-rm vieramatic.json

Had a couple of hiccups getting the bridge/device paired correctly, but confirming everything was paired correctly, here's the new vieramatic/json:
`{"4D454930-0200-1000-8001-8CC121609620":{"data":{"inputs":{"applications":{"0":{"id":"0387878700000032","name":"Media player"},"1":{"id":"0387878700000014","name":"DLNA server"},"2":{"id":"0387878700000016","name":"VIERA Link"},"3":{"id":"0387878700000001","name":"TV"},"4":{"id":"0387878700000009","name":"Menu"},"5":{"id":"0077777700000002","name":"Web Browser"},"6":{"id":"0387878700000026","name":"Paint"},"7":{"id":"0387878700000036","name":"Put Three"},"8":{"id":"0387878700000037","name":"Family Reversi"},"9":{"id":"0387878700000038","name":"Touch Connect"},"10":{"id":"0387878700000049","name":"Mirroring"},"11":{"id":"0010000200000001","name":"Netflix"},"12":{"id":"0070000200000001","name":"YouTube"},"13":{"id":"0010002000000001","name":"HSN Shop by Remote"},"14":{"id":"0010000300000001","name":"CinemaNow"},"15":{"id":"0070001000000001","name":"PlayJam"},"16":{"id":"0310005700000001","name":"Xumo"},"17":{"id":"0010001300000001","name":"VUDU HD Movies"},"18":{"id":"0387878700000022","name":"Jotter"},"19":{"id":"0070001700000001","name":"Classical Archives Player"}},"hdmi":[{"id":"2","name":"Receiver"}],"TUNER":{"hidden":0}},"ipAddress":"192.168.1.155","specs":{"friendlyName":"Living Room Panasonic","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"ZT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-8CC121609620"}}}}`

Would seem everything started up correctly:

[1/18/2022, 1:04:19 PM] [homebridge-vieramatic] Loaded homebridge-vieramatic v4.0.9 child bridge successfully
[1/18/2022, 1:04:19 PM] Loaded 0 cached accessories from cachedAccessories. [MACOfChildbridge].
[1/18/2022, 1:04:19 PM] [homebridge-vieramatic] handling '192.168.1.155' from config.json
[1/18/2022, 1:04:19 PM] Homebridge v1.3.9 (HAP v0.9.8) (homebridge-vieramatic) is running on port [PORTISHERE].
[1/18/2022, 1:04:19 PM] [homebridge-vieramatic] found a 'Panasonic VIErA' TV (ZT60) at '192.168.1.155' .
[1/18/2022, 1:04:19 PM] [homebridge-vieramatic] Initializing 'Living Room Panasonic' first time ever.
[1/18/2022, 1:04:19 PM] [homebridge-vieramatic] successfully loaded Living Room Panasonic

I still can't control the set (other than turning it on), and homebridge-UI won't let me edit the config directly, but at least for now, there are no more UUID crashes.

<img width="787" alt="Screen Shot 2022-01-18 at 1 19 36 PM" src="https://user-images.githubusercontent.com/23297381/150004106-c5bfde92-0445-4f01-bc0f-81b7c0a45ae1.png">

Maybe you can find something useful here? More data never hurts, right? 🤷‍♂️

**Comment by AntonioMeireles** [comment]
@tjm7844 many many thanks...

a) do you also have `friendlyName` set in your homebridge's config.json ? (could you paste the config anyway plz) 
b) platform plugins in general afaik won't work in bridgeed setups (homebridge design issue if i recall correctly)

looking into this. (and trying to spot a way to reproduce)

Thanks all gain for your patience!

**Comment by AntonioMeireles** [comment]
@bsoener @tjm7844 

could you also both give a try to `homebridge-vieramatic@4.0.10`. it should NOT crash whole homebridge anymore and also  give us (hopefully) a bit more precise error message... (attach it please) 

thanks in advance!

**Comment by bsoener** [comment]
latest update done and no error message. will wait until tomorrow and report back

**Comment by tjm7844** [comment]
I do have a friendly name. I removed the child bridge, and updated the plugin to 4.0.10.

Here's the config: 
`{
    "tvs": [
        {
            "friendlyName": "Living Room Panasonic",
            "ipAddress": "192.168.1.155",
            "mac": "8C:C1:21:60:96:20",
            "hdmiInputs": [
                {
                    "id": "2",
                    "name": "Receiver"
                }
            ],
            "disabledAppSupport": false,
            "customVolumeSlider": true
        }
    ],
    "platform": "PanasonicVieraTV"
}`

After doing the above, I restarted homebridge again, and saw this on startup: 
[1/18/2022, 11:32:58 PM] [PanasonicVieraTV] device: {"friendlyName":"Living Room Panasonic","ipAddress":"192.168.1.155","mac":"8C:C1:21:60:96:20","hdmiInputs":[{"id":"2","name":"Receiver"}],"disabledAppSupport":false,"customVolumeSlider":true}
[1/18/2022, 11:32:58 PM] [PanasonicVieraTV] specs: {"friendlyName":"Living Room Panasonic"}
[1/18/2022, 11:32:58 PM] [PanasonicVieraTV] Accessories must be created with a valid UUID.

It's not crashing the whole homebridge instance, but it won't let me re-pair the device. Will let it run and see if there's any different in the morning.

**Comment by AntonioMeireles** [comment]
@tjm7844 

can you post full logs plz (from homebridge early initialization ...) also, can you confirm that issue only happens if you restart homebridge with the TV in standby ?

thanks!

**Comment by AntonioMeireles** [comment]
@tjm7844, @bsoener 

i've pushed a new release `homebridge-vieramatic@4.0.11` (tagged as beta) so you need to `npm i homebridge-vieramatic@4.0.11` to consume it. it should give us a bit more robust behaviour/detailed info. Unsure if enough to fix whole thing.   

please attach here the newly generated boot logs... 

and thanks once again for all your patience!

**Comment by bsoener** [comment]
latest beta installed. The following error message from the log

```
[19/01/2022, 20:40:03] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 20:40:03] [PanasonicVieraTV] Using the previously cached ones:

 {"friendlyName":"Viera","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBC3C18D"}
```

```
[19/01/2022, 20:40:07] [PanasonicVieraTV] device: {"friendlyName":"Viera ","ipAddress":"192.168.178.115","mac":"xx:xx:xx:xx:xx:xx","hdmiInputs":[{"id":"1","name":"Denon"},{"id":"2","name":"PS5"}],"disabledAppSupport":false,"customVolumeSlider":true}
[19/01/2022, 20:40:07] [PanasonicVieraTV] specs: {"friendlyName":"Viera"}
[19/01/2022, 20:40:07] [PanasonicVieraTV] Accessories must be created with a valid UUID.
```

**Comment by AntonioMeireles** [comment]
@bsoener 

THANKS!. your data is in line with @tjm7844 previous one. that's the good news. the bad news is that i'm missing the obvious as it shouldn't just happen. FWIW the root issue is in `[19/01/2022, 20:40:07] [PanasonicVieraTV] specs: {"friendlyName":"Viera"}`. `specs`is not there and should. digging - this is some logic mistake i made somewhere. 

will get back to all of you soonish. 

(and thanks yet again  for all your patience!)

**Comment by AntonioMeireles** [comment]
@bsoener 

when you have the time install please `homebridge-vieramatic@4.0.12` (`npm i homebridge-vieramatic@4.0.12`), restart homebridge and paste output...

**Comment by bsoener** [comment]
```
[19/01/2022, 22:24:38] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (WT60) at '192.168.178.115' .

[19/01/2022, 22:24:38] [PanasonicVieraTV] Initializing 'Viera' first time ever.
[19/01/2022, 22:24:38] [PanasonicVieraTV] successfully loaded Viera
[19/01/2022, 22:24:38] Viera ED82 is running on port 46555.
```

**Comment by AntonioMeireles** [comment]
@bsoener, **THANKS**; now turn TV off plz, restart homebridge and past output again...

**Comment by bsoener** [comment]
So I installed the latest version. No error message comes. Now I could turn off my tv via the homeapp. Unfortunately I can no longer get it on. The slider moves back to off. Tv Remote ust activated.

**Comment by bsoener** [comment]
```
[19/01/2022, 22:30:44] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 22:30:44] [PanasonicVieraTV] Using the previously cached ones:

 {"friendlyName":"Viera","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"WT60","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBC3C18D"}
[19/01/2022, 22:30:48] [PanasonicVieraTV] device: {"friendlyName":"Viera ","ipAddress":"192.168.178.115","mac":"C0:D9:62:D3:BE:C1","hdmiInputs":[{"id":"1","name":"Denon"},{"id":"2","name":"PS5"}],"disabledAppSupport":false,"customVolumeSlider":true}
[19/01/2022, 22:30:48] [PanasonicVieraTV] specs: {"friendlyName":"Viera"}
[19/01/2022, 22:30:48] [PanasonicVieraTV] Accessories must be created with a valid UUID.
```

When restarting the Homebridge comes again this error message

**Comment by AntonioMeireles** [comment]
> Unfortunately I can no longer get it on. The slider moves back to off. Tv Remote ust activated.

can you explain this part a bit better ? not sure i understand. and logs please...

**Comment by AntonioMeireles** [comment]
@bsoener, humm,  are you sure that you are in `homebridge-vieramatic@4.0.12` and not `homebridge-vieramatic@4.0.11` ?

**Comment by bsoener** [comment]
I have the latest version on it. Restarted Homebridge. My Tv was reachable and no error log. About the Apple Homeapp I wanted to turn off the TV went well. Now I wanted to turn on again via Apple Homeapp again, and the On button goes from all off.

**Comment by bsoener** [comment]
mom

> @bsoener, humm, are you sure that you are in `homebridge-vieramatic@4.0.12` and not `homebridge-vieramatic@4.0.11` ?

mom

**Comment by bsoener** [comment]
Panasonic™ Viera™ TVs support

homebridge-vieramatic v4.0.12 

```
[19/01/2022, 22:39:26] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 22:39:26] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[19/01/2022, 22:39:29] [PanasonicVieraTV] A {
  "address": "192.168.178.115",
  "mac": "C0:D9:62:D3:BE:C1",
  "apps": {
    "error": {
      "code": "EHOSTUNREACH",
      "timings": {
        "start": 1642628366368,
        "socket": 1642628366369,
        "error": 1642628369441,
        "phases": {
          "wait": 1,
          "total": 3073
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 3500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      }
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
} {
  friendlyName: 'Viera ',
  ipAddress: '192.168.178.115',
  mac: 'C0:D9:62:D3:BE:C1',
  hdmiInputs: [ { id: '1', name: 'Denon' }, { id: '2', name: 'PS5' } ],
  disabledAppSupport: false,
  customVolumeSlider: true
}
[19/01/2022, 22:39:29] [PanasonicVieraTV] B {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[19/01/2022, 22:39:29] [PanasonicVieraTV] Using previously cached App listing.
[19/01/2022, 22:39:29] [PanasonicVieraTV] successfully loaded Viera
[19/01/2022, 22:39:29] Viera ED82 is running on port 33615.
[19/01/2022, 22:39:29] Please add [Viera ED82] manually in Home app. Setup Code: 031-45-154
```

**Comment by AntonioMeireles** [comment]
OK, so, no error now ? right, i.e. things behave when you restart homebridge regardless of TV being ON or OFF ? or no ?

**Comment by bsoener** [comment]
I no longer get an error message. Only this when restarting the homebridge

```
19/01/2022, 22:39:26] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 22:39:26] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
```

**Comment by AntonioMeireles** [comment]
right, but only **when** TV is off (you don't get that one - the `[PanasonicVieraTV] Using the previously cached ones` part when TV is ON and you restart homebridge. is this correct ? 
also, now TV / homekit behaves ?

**Comment by bsoener** [comment]
With the homeapp I can unfortunately not switch the tv on and off.

**Comment by AntonioMeireles** [comment]
oh, missed last line. 
a)  drop the TV from the home app
b) remove (see earlier) the `vieramatic.json` and restart homebridge
c) add TV to home app again. 

hopefully that may be enought to fix things (i.e. you may be getting side effects from past woes)

**Comment by bsoener** [comment]
So, I kicked Viera out of the homeapp, deleted .json via homebridge terminal, restarted the homebridge, added Tv back into the homeapp. But can not turn it on. The slider falls back to off.

**Comment by AntonioMeireles** [comment]
:/ and nothing in logs ? 

can you restart homebridge with `-D` option, and then attach here its' output ? (`-D` adds a 'bit' more debug logging to its output. should tell us where things are tanking now)

**Comment by bsoener** [comment]
please be more specific. how do i do that?

**Comment by AntonioMeireles** [comment]
something along (https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode)

**Comment by bsoener** [comment]
```
[19/01/2022, 23:12:39] [PanasonicVieraTV] getSpecs: RequestError: connect EHOSTUNREACH 192.168.178.115:55000
    at ClientRequest.<anonymous> (file:///usr/local/lib/node_modules/homebridge-vieramatic/node_modules/got/dist/source/core/index.js:792:107)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  input: undefined,
  code: 'EHOSTUNREACH',
  timings: {
    start: 1642630356348,
    socket: 1642630356351,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1642630359442,
    abort: undefined,
    phases: {
      wait: 3,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 3094
    }
  },
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: 3500,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      accept: 'application/xml',
      'cache-control': 'no-cache',
      'content-type': 'application/xml; charset="utf-8"',
      host: '192.168.178.115:55000',
      pragma: 'no-cache',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 0,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'http://192.168.178.115:55000/nrc/ddd.xml',
      origin: 'http://192.168.178.115:55000',
      protocol: 'http:',
      username: '',
      password: '',
      host: '192.168.178.115:55000',
      hostname: '192.168.178.115',
      port: '55000',
      pathname: '/nrc/ddd.xml',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined
  }
}
[19/01/2022, 23:12:39] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 23:12:39] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
```

**Comment by AntonioMeireles** [comment]
OK, great! pass plz the output you get when you try to turn on the TV

**Comment by AntonioMeireles** [comment]
AFAICT your TV needs to be awaken via WOL (wake on lan)

**Comment by AntonioMeireles** [comment]
also, getting a bit late - if you prefer we can continue tommorrow (after 8pm UTC)

**Comment by bsoener** [comment]
```
[19/01/2022, 22:59:31] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[19/01/2022, 22:59:31] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[19/01/2022, 22:59:34] [PanasonicVieraTV] A {
  "address": "192.168.178.115",
  "mac": "C0:D9:62:D3:BE:C1",
  "apps": {
    "error": {
      "code": "ETIMEDOUT",
      "timings": {
        "start": 1642629571460,
        "socket": 1642629571462,
        "error": 1642629574962,
        "phases": {
          "wait": 2,
          "total": 3502
        }
      },
      "name": "TimeoutError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 3500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      },
      "event": "request"
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
} {
  friendlyName: 'Viera ',
  ipAddress: '192.168.178.115',
  mac: 'C0:D9:62:D3:BE:C1',
  hdmiInputs: [ { id: '1', name: 'Denon' }, { id: '2', name: 'PS5' } ],
  disabledAppSupport: false,
  customVolumeSlider: true
}
[19/01/2022, 22:59:34] [PanasonicVieraTV] B {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[19/01/2022, 22:59:34] [PanasonicVieraTV] Using previously cached App listing.
[19/01/2022, 22:59:35] [PanasonicVieraTV] successfully loaded Viera
[19/01/2022, 22:59:35] Viera ED82 is running on port 45743.
[19/01/2022, 22:59:35] Please add [Viera ED82] manually in Home app. Setup Code: 031-45-154
[19/01/2022, 23:02:47] [Homebridge UI] [homebridge-vieramatic] Incoming Request: /ping
[19/01/2022, 23:02:48] [Homebridge UI] [homebridge-vieramatic] ---> (ping) 192.168.178.115 false
[19/01/2022, 23:02:56] [Homebridge UI] [homebridge-vieramatic] Terminating child process...
[19/01/2022, 23:02:56] [Homebridge UI] [homebridge-vieramatic] Child process ended
[19/01/2022, 23:12:23] [Homebridge UI] Starting terminal session
[19/01/2022, 23:18:09] [Homebridge UI] Terminal session ended.
```

**Comment by AntonioMeireles** [comment]
you don't get extra output when you try to turn TV on / off ?

**Comment by bsoener** [comment]
no

**Comment by AntonioMeireles** [comment]
@bsoener  need to think on this... :| - will get back to you tommorrow!

@tjm7844  - quick question - you also set a mac address right in homebridge config.json, right ? 


THANKS ALL for your patience!

**Comment by tjm7844** [comment]
Yes - I manually set the MAC in the config. Apologies for the delay, I haven't had access to the TV, and then had some issues installing the beta version. I definitely confirmed the UUID message was only coming up when restarting with the TV off.

I've actually done a fair bit of work with this generation of sets in pre-homebridge apps (iRule, Roomie remote, etc), and WOL is the only mechanism I'm aware of to power on the set (and therefore needs the MAC, and also only works hardwired).

**Comment by bsoener** [comment]
Usually yes. But I will have a look tomorrow.

**Comment by AntonioMeireles** [comment]
@bsoener , @tjm7844 


just pushed (again as beta) `homebridge-vieramatic@4.0.13` (consumable by `npm i homebridge-vieramatic@4.0.13` followed by an homebridge restart). It 's a bit more noisier and should help us to isolate core remaining issue.

So, could you please install it and after restarting homebridge attach here the homebridge console logs (both from homebridge startup and around attempts to turn TV ON/OFF via homekit (with both the TV powered ON and off)

thanks!

**Comment by bsoener** [comment]
```
[20/01/2022, 16:24:54] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[20/01/2022, 16:24:54] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[20/01/2022, 16:24:57] [PanasonicVieraTV] userConfig {
  "friendlyName": "Viera ",
  "ipAddress": "192.168.178.115",
  "mac": "xx:xx:xx:xx:xx:xx",
  "hdmiInputs": [
    {
      "id": "1",
      "name": "Denon"
    },
    {
      "id": "2",
      "name": "PS5"
    }
  ],
  "disabledAppSupport": false,
  "customVolumeSlider": true
}
[20/01/2022, 16:24:57] [PanasonicVieraTV] accessory.context.device {
  "address": "192.168.178.115",
  "mac": "C0:D9:62:D3:BE:C1",
  "apps": {
    "error": {
      "code": "EHOSTUNREACH",
      "timings": {
        "start": 1642692294423,
        "socket": 1642692294424,
        "error": 1642692297521,
        "phases": {
          "wait": 1,
          "total": 3098
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 3500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      }
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
}
[20/01/2022, 16:24:57] [PanasonicVieraTV] Using previously cached App listing.
[20/01/2022, 16:24:57] [PanasonicVieraTV] successfully loaded Viera
[20/01/2022, 16:24:57] Viera ED82 is running on port 35697.
```

**Comment by AntonioMeireles** [comment]
@bsoener 

**Thanks**! afterwards, when you try to turn TV ON/OFF you should also get some output... attach it please. hopefully answer will be somewhere there ...

**Comment by bsoener** [comment]
I'll turn on the TV and report back in a moment.

**Comment by bsoener** [comment]
off status:

```
[20/01/2022, 16:40:24] [Homebridge UI] [homebridge-vieramatic] found a 'Panasonic VIErA' TV (WT60) at '192.168.178.115' .
[20/01/2022, 16:40:30] [Homebridge UI] [homebridge-vieramatic] Terminating child process...
[20/01/2022, 16:40:30] [Homebridge UI] [homebridge-vieramatic] Child process ended
[20/01/2022, 16:41:17] [PanasonicVieraTV] (setPowerStatus) this.device: {
  "address": "192.168.178.115",
  "mac": "xx:xx:xx:xx:xx:xx",
  "apps": {
    "error": {
      "code": "EHOSTUNREACH",
      "timings": {
        "start": 1642692294423,
        "socket": 1642692294424,
        "error": 1642692297521,
        "phases": {
          "wait": 1,
          "total": 3098
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 3500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      }
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
}
[20/01/2022, 16:41:17] [PanasonicVieraTV] (setPowerStatus) this.userConfig: {
  "friendlyName": "Viera ",
  "ipAddress": "192.168.178.115",
  "mac": "C0:D9:62:D3:BE:C1",
  "hdmiInputs": [
    {
      "id": "1",
      "name": "Denon"
    },
    {
      "id": "2",
      "name": "PS5"
    }
  ],
  "disabledAppSupport": false,
  "customVolumeSlider": true
}
[20/01/2022, 16:41:17] [PanasonicVieraTV] (setPowerStatus) 0 true
[20/01/2022, 16:41:17] [PanasonicVieraTV] Turned TV into STANDBY
```

**Comment by AntonioMeireles** [comment]
and TV went in Standby ? afterwards were you able to get it back ON ? (either yes or no logs please)

**Comment by bsoener** [comment]
on status:

```
[20/01/2022, 16:43:30] [PanasonicVieraTV] (setPowerStatus) this.device: {
  "address": "192.168.178.115",
  "mac": "xx:xx:xx:xx:xx:xx",
  "apps": {
    "error": {
      "code": "EHOSTUNREACH",
      "timings": {
        "start": 1642692294423,
        "socket": 1642692294424,
        "error": 1642692297521,
        "phases": {
          "wait": 1,
          "total": 3098
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 3500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      }
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
}
[20/01/2022, 16:43:30] [PanasonicVieraTV] (setPowerStatus) this.userConfig: {
  "friendlyName": "Viera ",
  "ipAddress": "192.168.178.115",
  "mac": "xx:xx:xx:xx:xx:xx",
  "hdmiInputs": [
    {
      "id": "1",
      "name": "Denon"
    },
    {
      "id": "2",
      "name": "PS5"
    }
  ],
  "disabledAppSupport": false,
  "customVolumeSlider": true
}
[20/01/2022, 16:43:30] [PanasonicVieraTV] (setPowerStatus) 1 false
[20/01/2022, 16:43:30] [PanasonicVieraTV] sending WOL packets to awake TV
[20/01/2022, 16:43:31] [PanasonicVieraTV] Turned TV ON
```

**Comment by bsoener** [comment]
When switching on, the on button goes back to off. So it does not turn on

**Comment by AntonioMeireles** [comment]
@bsoener, your homebridge server is same network / vlan as TV right ? 

if so issue identified (afaict) - with the move to ESM the wol lib we consume seems to have stopped behaving. let me digg on this a bit more. apparently issue identified now. 


Thanks **yet** again!

**Comment by bsoener** [comment]
So it tried with lan and wifi, unfortunately with both the problem that I can not turn off the TV. if you find ne solution for this would be great.

**Comment by bsoener** [comment]
So I can turn off the TV. I can't turn it on. I will try it again later.

**Comment by AntonioMeireles** [comment]
@bsoener, @tjm7844 

test both please `homebridge-vieramatic@4.0.14`  (tagged again as beta and consumable by `npm i homebridge-vieramatic@4.0.14` followed by an homebridge restart)

**IF** i'm right it has the fix for this issue... please confirm (crossing fingers)

All the best, 

António

**Comment by bsoener** [comment]
I turned on the TV with the remote control. On the home app it shows off. On/off button no longer responds.

**Comment by AntonioMeireles** [comment]
OK, progress!. attach matching logs plz. i suspect now the issue is a timings one... your TV is oldish and just takes a bit to wake up and we may need to accomodate that.

**Comment by bsoener** [comment]
The TV is only 6 years old and is still in very good condition :D

**Comment by tjm7844** [comment]
Currently having issues discovering the set within Homebridge, so I'm going to work through that (can't test actual functionality without that, clearly). Thanks to both of you for continuing to work through it!

**Comment by AntonioMeireles** [comment]
@bsoener, @tjm7844 


please give a try to test just released `homebridge-vieramatic@4.0.15` (tagged again as beta and consumable by npm i `homebridge-vieramatic@4.0.15` followed by an homebridge restart) and report back on its overall behaviour (with logs attached)

Thanks in advance!

**Comment by tjm7844** [comment]
Question: after running the manual version install command, should the new version be reflected in either HomebridgeUI or the logs? I'm seeing package changes on the install, but the version numbers aren't updating anywhere else. If there's a command to manually check the version of a specific plugin from the command line, I haven't found it yet...Want to make sure I'm on the correct version (I haven't seen any behavior changes yet, but I still haven't gotten my TV to be re-paired into Homebridge, so am just looking at the log entries. I'm planning on wiping my config for this set and trying everything from scratch, but in the meantime would like to be able to ensure the code I have is actually up to date :)

**Comment by AntonioMeireles** [comment]
you can see installed versions in HomebridgeUI per

<img width="996" alt="image" src="https://user-images.githubusercontent.com/743527/150581131-fa9a746b-bc62-
4591-b5c2-c1729f2f753d.png">

`npm ls` gives you the installed versions on the cli. 

btw, what issues are you experiencing when re-pairing your TV ?

**Comment by bsoener** [comment]
Hi. Thank you for your effort. I have now installed the latest version and unfortunately I can not turn on my TV.

**Comment by AntonioMeireles** [comment]
> Hi. Thank you for your effort. I have now installed the latest version and unfortunately I can not turn on my TV.

attach logs please, we're getting close(r). also, can you email me (email is the one in git commit logs) directly to see if we can arrange an off-line faster low-latency way to finish debugging this ? :-) 

All the best, 

António

**Comment by tjm7844** [comment]
> you can see installed versions in HomebridgeUI per
> 
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/743527/150581605-1124e9a1-bada-4444-8013-85dec08ebc02.png">
> 
> `npm ls` gives you the installed versions on the cli.
> 
> btw, what issues are you experiencing when re-pairing your TV ?

The TV just isn't coming up as an accessory. I expect this has something to do with my moving it to a child bridge and then back again, but monkeying with the vieramatic.json files in there probably didn't help matters. As I mentioned, I'm going to try a full uninstall of the package, clearing out the config/vieramatic.json cache/etc, and see if that helps matters.

To the matter at hand, when I run the `npm i veramatic@version` command, my UI isn't updating the version number, so it would seem something isn't quite clicking there.

**Comment by AntonioMeireles** [comment]
> To the matter at hand, when I run the `npm i homebridge-vieramatic@version` command, my UI isn't updating the version number, so it would seem something isn't quite clicking there.

you need to restart homebridge for the change to have effect.

**Comment by tjm7844** [comment]
Yeah, I have been. It even shows a package having been changed when I run the update, but the UI doesn't show the new version (hence why I manually wanted to check from the command line)

**Comment by AntonioMeireles** [comment]
humm, depending on your setup you may need to run `npm i homebridge-vieramatic@version -g`)

**Comment by tjm7844** [comment]
Could be that. I'm running on a debian VM running on an ESXI host, but have done everything standard per the docs. I'll give that a try after I flush out the old data and reinstall.

**Comment by AntonioMeireles** [comment]
> Could be that. I'm running on a debian VM running on an ESXI host, but have done everything standard per the docs. I'll give that a try after I flush out the old data and reinstall.
@tjm7844, 
please do make sure that you do not have any firewall between your homebridge VM and your TVs blocking **(UDP) port 9** (as otherwise the WOL magic packets won't ever hit the TV)

**Comment by tjm7844** [comment]
I'll verify, but I don't expect that's an issue as WOL had never been my problem. Off was my issue :)

**Comment by bsoener** [comment]
On the homeapp I press the on button and on the log from the homebridge only this log appears. After a short time this on button on the homeapp jumps back to off.

```
[21/01/2022, 20:17:06] [PanasonicVieraTV] (setPowerStatus) 1 false
[21/01/2022, 20:17:06] [PanasonicVieraTV] sending WOL packets to awake TV
[21/01/2022, 20:17:08] [PanasonicVieraTV] Turned TV ON
```
Restart log I get this:

```
[21/01/2022, 20:20:25] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[21/01/2022, 20:20:25] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[21/01/2022, 20:20:25] [PanasonicVieraTV] userConfig {
  "friendlyName": "Viera ",
  "ipAddress": "192.168.178.115",
  "mac": "xx:xx:xx:xx:xx:xx",
  "hdmiInputs": [
    {
      "id": "1",
      "name": "Denon"
    },
    {
      "id": "2",
      "name": "PS5"
    }
  ],
  "disabledAppSupport": false,
  "customVolumeSlider": true
}
[21/01/2022, 20:20:25] [PanasonicVieraTV] accessory.context.device {
  "address": "192.168.178.115",
  "apps": {
    "error": {
      "code": "EHOSTUNREACH",
      "timings": {
        "start": 1642792825122,
        "socket": 1642792825124,
        "error": 1642792825201,
        "phases": {
          "wait": 2,
          "total": 79
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {
          "request": 1500
        },
        "prefixUrl": "",
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_GetAppList xmlns:u=\"urn:panasonic-com:service:p00NetworkControl:1\">None</u:X_GetAppList></s:Body></s:Envelope>",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept": "application/xml",
          "cache-control": "no-cache",
          "content-type": "application/xml; charset=\"utf-8\"",
          "host": "192.168.178.115:55000",
          "pragma": "no-cache",
          "soapaction": "\"urn:panasonic-com:service:p00NetworkControl:1#X_GetAppList\"",
          "content-length": "285",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 0,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "POST",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": false,
        "responseType": "text",
        "url": "http://192.168.178.115:55000/nrc/control_0",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true
      }
    }
  },
  "auth": {},
  "specs": {
    "friendlyName": "Viera",
    "manufacturer": "Panasonic",
    "modelName": "Panasonic VIErA",
    "modelNumber": "WT60",
    "requiresEncryption": false,
    "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
  }
}
[21/01/2022, 20:20:25] [PanasonicVieraTV] Using previously cached App listing.
[21/01/2022, 20:20:25] [PanasonicVieraTV] successfully loaded Viera
[21/01/2022, 20:20:25] Viera ED82 is running on port 38483.
[21/01/2022, 20:20:25] Please add [Viera ED82] manually in Home app. Setup Code: xxx-xx-xxx

```

**Comment by AntonioMeireles** [comment]
@bsoener 

OK, issue at macro level is ...
- we send 10 WOL magic packets to the TV (that takes 1 sec (10 magic pkts sent with 100ms interval)
- then we wait an extra sec and then we try to "talk" with the TV. (and update Homebridge status assuming TV is already waked up)

so basically we're expecting that the between receiving the magic packets and becoming responsive (at API level) the TV won't take longer than 2seconds. which according to you isn't being the case. 

At the same time, each 5secs we refresh TVs state (so even if it takes longer than 2 secs for TV to become responsive) at next refresh we'd expect it would be detected as up...

This is why we need a more spedite way of debugging this :-) (just email me ;-) )

**Comment by tjm7844** [comment]
@AntonioMeireles, thank you. The global flag was what was necessary to get the beta version installed for me. It's now showing correctly in the UI. Also, purging the plugin entirely, making sure all the various caches were removed, etc, allowed me to find and re-pair the set to homebridge. 

It appears that I'm seeing similar logs to @bsoener on restart/attempting to WOL. I'm happy to email them if you'd like to see them.

Also, if it's helpful, I just did a (very unscientific) test of my TV's startup time using my phone's stopwatch, and it appears to be roughly 6.5-7 seconds (6.63, 6.51 in my two tests).

**Comment by AntonioMeireles** [comment]
@tjm7844 

7secs ! ouch. even so, after those 7secs TV should then appear as ON to homekit ... can you mail me ... i just need some spedited way to debug this ...

**Comment by bsoener** [comment]
What exactly do you need from me? Where is your email address?

**Comment by AntonioMeireles** [comment]
> What exactly do you need from me? Where is your email address?

@bsoener 

Hi, morning!

a priori i already have all info i need. I did a live debug session on @tjm7844 's TV set last night. but THANKS!...

I'll push soonish a new version with more polish and more fixed issues.

**Comment by AntonioMeireles** [comment]
@bsoener, @tjm7844 

please update and give a try to just released `homebridge-vieramatic@4.0.17` (tagged again as beta and consumable by `npm i homebridge-vieramatic@4.0.17 -g` followed by an homebridge restart) and report back on its overall behaviour.

it should fix the issue of TV being ON but not being recognized as that (after being awaken) by the plugin (just found last night that older TVs advertise their availability in a slightly different way than recent ones). 
It should also workaround a strange issue we've found regarding WOL behaviour (which doesn't seem exactly the same in all platforms (!)). 

A great weekend for you all, and many thanks for your patience!

Thanks in advance! 

António

**Comment by bsoener** [comment]
Latest version installed. Unfortunately, my TV does not wake up. on the Hombridge log comes unfortunately no message.

```

[22/01/2022, 14:46:01] [PanasonicVieraTV] Unable to fetch specs from TV at '192.168.178.115'.
[22/01/2022, 14:46:01] [PanasonicVieraTV] Using the previously cached ones:

 {
  "friendlyName": "Viera",
  "manufacturer": "Panasonic",
  "modelName": "Panasonic VIErA",
  "modelNumber": "WT60",
  "requiresEncryption": false,
  "serialNumber": "4D454930-0200-1000-8001-20C6EBC3C18D"
}
[22/01/2022, 14:46:01] [PanasonicVieraTV] Using previously cached App listing.
[22/01/2022, 14:46:01] [PanasonicVieraTV] successfully loaded Viera
[22/01/2022, 14:46:01] Viera ED82 is running on port 36021.
```

**Comment by AntonioMeireles** [comment]
@bsoener 

sorry to hear that. let's wait a bit for @tjm7844 feedback. if i hadn't make any aditional mistake (and his TV behaves) that means your TV is from yet another generation with slight different behaviout we'd need to accomodate ...

**Comment by tjm7844** [comment]
Sorry for the delay! TV has been in use this morning and just had a chance to test :) Everything still appears to be working fine for me after the update to 4.0.17. @AntonioMeireles, I never did unlink from your live code changes, but the update did appear to process and shows the new version.

Just want to confirm that I am set up correctly so my feedback is representative.

Also, there is some new behavior that we found while testing this version, wherein the TV will turn on, then the HomeKit tile flips to off, and then corrects itself back to on. Just so anyone who is reading this is aware.

**Comment by AntonioMeireles** [comment]
@tjm7844 

quick question - is you TV connect to the network via wired or wirelessly ?

**Comment by tjm7844** [comment]
Wired - this generation of sets doesn't support WOL from a wireless connection.

**Comment by AntonioMeireles** [comment]
@bsoener 

and yours ? wired or wirelessly ?

**Comment by bsoener** [comment]
currently via wifi

**Comment by bsoener** [comment]
I will try later via lan. then give feedback

**Comment by AntonioMeireles** [comment]
@bsoener 

do plz... will publish soon an hack that may make it behave both ways (crossing fingers)

**Comment by bsoener** [comment]
connected via lan and sorry does not go on and off

**Comment by AntonioMeireles** [comment]
@tjm7844 

please report on just pushed `homebridge-vieramatic@4.0.18`. i now use an handmade WOL function. if i did it right it things **should** continue working for wired TV sets (i.e. they should still be wakable as in 4.0.17). OTOH sets connected wirelessly  should also wake up now (if all will do, or only recent ones dunno yet).

**Comment by AntonioMeireles** [comment]
@bsoener 

so, you may have a TV of yet another generation that behaves sligtly differently too ...

on you homebridge box do ...
- `git clone https://github.com/AntonioMeireles/homebridge-vieramatic.git`
- `(cd homebridge-vieramatic &&  git log | grep -ia signed | head -n 1)`

this last command will get you my email address. just email me and i'll reply back to you quickly :-)

**Comment by tjm7844** [comment]
On/off still working for me on 4.0.18.

**Comment by AntonioMeireles** [comment]
@tjm7844 

just published  `homebridge-vieramatic@4.0.20` (as non beta) per @tjm7844  feedback. 

debugging of @bsoener issues (which seem to be separate ones) will continue.
